### PR TITLE
Receipt logo

### LINKED ISSUE #19: Club logo in receipt
**Describe the bug**
Currently, a constant image is being displayed as the logo on the event receipts.

**To Reproduce**
- Check any receipt

**Expected behavior**
Club's logo should be displayed. If logo is not set, show some dummy image or do not show any logo.

**Screenshots**
screenshot from 2018-12-26 22-27-55

Check line 80 of `eventpdf.ejs`

### PR DESCRIPTION
**Pull request by PriyamAgrawal**
### Description
Bug Fix: Fixes club logo displayed in receipt, now displaying the club logo stored in the folder names by the club id. No logo displayed on absence of the file.

Fixes #19 

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by bhawesh96** [comment]
@PriyamAgrawal The way you're checking if the logo exists needs some modification. If the club has uploaded a logo, its URL be available as `profilePicURL`. If the club removes the logo or has not uploaded, `profilePicURL` will be null

**Comment by PriyamAgrawal** [comment]
Logic modified. The sample DB didn't had the required sub-node, so got confused of the implementation.

File: controllers/eventController.js [hunk 1]
```diff
@@ -38,62 +38,67 @@ exports.generate_pdf = function (req, res) {
...
+        room_list: roomlist,
+        isVisible: visibility,
+        Notes: notes,
+        fa_name: snapshot.val().FA_name,
+        ad_name: AD_NAME,
+        so_name: SO_NAME,
+        fa_date: snapshot.val().FA_date,
+        ad_date: snapshot.val().AD_date,
+        so_date: snapshot.val().SO_date,
+        club_logo: profilePicURL
```
Comment (bhawesh96) [inline controllers/eventController.js]: Does this handle the null case @PriyamAgrawal ?
